### ISSUE TITLE
Update k8s-ei-operator and merge with k8s-api-operator

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/k8s-ei-operator#19]
**Description:**
From APIM 4.0 onwards, we are planning to provide a unified user experience in the operator. We should make all the necessary enhancement to the k8s-ei-operator while merging with the k8s-api-operator.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by abeykoon** [comment]
This task is performed. Merged EI operator into APIM K8s operator. Also revamped the code in a more structured way so that we can introduce new features easily. 

Following new features were introduced. 

- horizontal pod scaling capability 
- define required resources and resource limits 
- ability to configure liveness and readiness probes
- inject all env variables in a configMap capability 
- ability to define reconcile interval for integration controller 
- bug fixes in ingress creation and more...

**Comment by abeykoon** [comment]
Closing as task is complated.
